### ISSUE TITLE
I run "npm run dev", and visit localhost:2992, but only get a list of files

### ISSUE THREAD

**Issue by lukeqi** [Paqmind/react-ultimate#98]
The project is great and very useful.

But when I download, npm install and npm run dev, I visit localhost: 2992 but I only get a page of a list of files.

Am I doing wrong? How can I see the page like in the demo?

Many thanks!

**Comment by ivan-kleshnin** [comment]
Hi @lukeqi. Nice to hear that.

Yes, my instructions miss some critical points. So thank you for your question.
I will update README accordingly.

`localhost:2992` is a Webpack endpoint. You should not access this URL.

According to the [Run section](https://github.com/Paqmind/react-ultimate#run) you need to run both `webpack` and `nodemon`. Then (and this part is missing) you need to access backend endpoint.

Nodemon logs
`2016-03-16 09:32:08 INFO Listening on port 3000`

So access a `localhost:3000` URL

Feel free to ask any additional questions in case you're stuck :+1:

**Comment by lukeqi** [comment]
Hi @ivan-kleshnin ,

I made it work! Thank you for your explanation!

I do also think there too many "starters" but too few (if any) like this one!

**Comment by ivan-kleshnin** [comment]
No problem, you're welcome. 

I should admit I'm far from being satisfied with what I've done here. 
But I doubt it's possible to significantly improve it, keeping React in game.
So if you know (or suppose) how to make something better – I'm always open to discussion.

**Comment by lukeqi** [comment]
As Redux becomes more and more popular, I am wondering if you could develop a version that is based on redux, which I think will make your project more welcomed, : )
Like the tools erikras/react-redux-universal-hot-example used.

**Comment by lukeqi** [comment]
As many have been familiar with the tools with Redux, there is a learning curve switching to the other tools (packages).
I want to say the designing of paging and filter is really great and I benefit a lot from it!

**Comment by lukeqi** [comment]
So if there is a version used with Redux and with more popular packages I bet this project will be very popular, say I guess stared by a thousand, : p

**Comment by ivan-kleshnin** [comment]
> I bet this project will be very popular, say I guess stared by a thousand

Maybe :) I never really attempted to promote this project. 
Those texts were written for potential clients rather that devs. 
It's not hard to notice in the hindsight.

When I started this repo (half year ago) I had only few months of JS experience.
My key goals were 1) learn React 2) learn frontend 3) implement a cool architecture.
I kinda succeeded with first two and kinda failed with the third. 
Redux was not available at that moment.

Now I could reimplement it with Redux but I believe CycleJS is much more interesting. 
So, in short, I'm going to rewrite it in CycleJS rather than Redux. 

In my opinion you can't get a pretty architecture with incomplete reactivity. 
And React is a real obstacle here.

---

Paging is super complex topic. If you want to allow random page access (relocate from page 1 to page 10...) you need to allow "holes" in the pagination. And you're into much more complex architecture in the result. You can simplify a present arch. by removing `total` (this is the update I'm going to publish soon). But it still will be very complex.

My conclusion: prefer "on-demand" `prev / next` kind of pagination if you have a choice.
This deserves a separate article. But think how big sites like Facebook / Twitter almost never provide a pagination. Because any implementation would fail on their data size.

**Comment by lukeqi** [comment]
Yeah...I have coded for a long time but just have learnt JS, React and front-end development. I have been thinking for the implementation of pagination and did not realize until now that this issue is the main rock of a website, if we to design a good comments / pagination system. But tutorials seldom elaborate on this.

**Comment by ivan-kleshnin** [comment]
Right. It's striking how far it goes. There are many articles about UI / UX aspects of pagination options.
Like "if you have a few items go with pages, if you have many items go with infinite scroll...".
But I had found no information about state representation at that moment. 
And probably nothing is really published.
